# Generated by Django 4.1 on 2022-09-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0003_rename_create_ad_ad_created_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='created_ad',
            new_name='create_ad',
        ),
    ]
