# Generated by Django 4.1 on 2022-09-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='AdFileBr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletinboardapp.ad')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletinboardapp.feedfile')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='file',
            field=models.ManyToManyField(through='bulletinboardapp.AdFileBr', to='bulletinboardapp.feedfile'),
        ),
    ]
