# Generated by Django 4.0.4 on 2022-09-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0007_feedfile_adfilebr_ad_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfile',
            name='file',
            field=models.FileField(upload_to='templates/files/%Y/%m/%d'),
        ),
    ]
