# Generated by Django 4.0.4 on 2022-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0008_alter_feedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfile',
            name='file',
            field=models.FileField(upload_to='static/files/%Y/%m/%d'),
        ),
    ]
