# Generated by Django 4.1 on 2022-09-28 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletinboardapp', '0009_alter_feedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authors',
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ad',
            name='file',
        ),
        migrations.AlterField(
            model_name='feedfile',
            name='file',
            field=models.FileField(default='default_files', upload_to='static/files/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='AdFileBr',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='ad',
            name='file',
            field=models.ForeignKey(default='default_file', on_delete=django.db.models.deletion.CASCADE, to='bulletinboardapp.feedfile'),
        ),
    ]
