# Generated by Django 4.1 on 2022-09-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0010_remove_author_authors_alter_ad_author_remove_ad_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletinboardapp.feedfile'),
        ),
    ]
