# Generated by Django 4.1 on 2022-09-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_ad', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletinboardapp.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletinboardapp.category')),
            ],
        ),
    ]
