# Generated by Django 4.1 on 2022-09-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0002_category_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='create_ad',
            new_name='created_ad',
        ),
    ]
