# Generated by Django 4.1 on 2022-09-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboardapp', '0004_rename_created_ad_ad_create_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='create_ad',
            new_name='created_ad',
        ),
    ]
